// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace ServicePoint.BindGen
{
    

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct SPByteSlice
    {
        public byte* start;
        public nuint length;
    }



}
