[workspace]
resolver = "2"
members = [
    "servicepoint2",
    "servicepoint2-binding-cs",
    "examples/announce",
    "examples/game_of_life",
    "examples/moving_line",
    "examples/wiping_clear",
    "examples/random_brightness"
]
