language = "C"
include_version = true
cpp_compat = true

############################ Code Style Options ################################

braces = "SameLine"
line_length = 80
tab_width = 4
documentation = true
documentation_style = "auto"
documentation_length = "full"
line_endings = "LF"

############################# Codegen Options ##################################

style = "both"
sort_by = "Name"
usize_is_size_t = true

[parse]
parse_deps = false

[parse.expand]
all_features = true
