[package]
name = "servicepoint-binding-cs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
servicepoint2 = { path = "../servicepoint2" }

[build-dependencies]
csbindgen = "1.8.0"
