[package]
name = "announce"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
servicepoint2 = { path = "../.." }
log = "0.4.21"
env_logger = "0.11.3"
