[package]
name = "random_brightness"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
servicepoint2 = { path = "../.." }
clap = { version = "4.5.4", features = ["derive"] }
rand = "0.8.5"
env_logger = "0.11.3"
log = "0.4.21"
