[package]
name = "random_brightness"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
servicepoint2 = { path = "../../servicepoint2" }
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"

rand = "0.8"
