[package]
name = "moving_line"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
servicepoint = { path = "../../crates/servicepoint" }
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
