language = "C"
include_version = true
cpp_compat = true

############################ Code Style Options ################################

braces = "SameLine"
line_length = 80
tab_width = 4
documentation = true
documentation_style = "auto"
documentation_length = "full"
line_endings = "LF"

############################# Codegen Options ##################################

style = "both"
sort_by = "Name"
usize_is_size_t = true

[defines]
"feature = compression-gz" = "SP2_FEATURE_compression_gz"
"feature = compression-bz" = "SP2_FEATURE_compression_bz"
"feature = compression-lz" = "SP2_FEATURE_compression_lz"
"feature = compression-zs" = "SP2_FEATURE_compression_zs"
#"feature = c-api" = "SP2_FEATURE_c-api"

[export]
prefix = "sp2_"

[parse.expand]
features = ["c-api"]
all_features = true
