name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build default features
      run: cargo build --all --verbose
    - name: build default features -- examples
      run: cargo build --examples --verbose
    - name: test default features
      run: cargo test --all --verbose

    - name: build all features
      run: cargo build --all-features --verbose
    - name: build all features -- examples
      run: cargo build --all-features --examples --verbose
    - name: test all features
      run: cargo test --all --all-features --verbose
