name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update repos
        run: sudo apt-get update -qq
      - name: Install rust toolchain
        run: sudo apt-get install -qy cargo rust-clippy
      - name: install lzma
        run: sudo apt-get update && sudo apt-get install -y liblzma-dev

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
        
      - name: build default features
        run: cargo build --all --verbose
      - name: build default features -- examples
        run: cargo build --examples --verbose
      - name: test default features
        run: cargo test --all --verbose

      - name: build all features
        run: cargo build --all-features --verbose
      - name: build all features -- examples
        run: cargo build --all-features --examples --verbose
      - name: test all features
        run: cargo test --all --all-features --verbose
